name=Draco
version=1.0
author=Joel Perez Izquierdo
maintainer=https://github.com/jpizquierdo/
sentence=A C++ Arduino library to make a DIY water control system. For all Arduino/Genuino boards.
paragraph=This library uses some common electronics devices to make an automathized water control system.
category=Device Control
url=https://github.com/jpizquierdo/Draco
architectures=*
