#watering system
#sensor:
- platform: template
  sensors:
    water_time_1:
      friendly_name: 'Water Time 1'
      value_template: "{{'{:02d}:{:02d}'.format(states('input_number.wateringhourstart_1') | int, states('input_number.wateringminutesstart_1') | int) }}"

- platform: time_date
  display_options:
    - 'time'